version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: hourly
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: hourly
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: hourly
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: hourly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
